"""Regenerate the known-answer table in docs/METHOD.md from the committed runs.

Three tables in this repo drifted apart: docs/METHOD.md section 10,
showcase/track_record.json and showcase/validation.md disagreed on Rhodes'
verdict and on Grunheide's interval, because METHOD.md was written by hand and
the showcase runs moved underneath it (Rhodes was re-run in wide mode and became
REAL). Hand-editing it again would just restart the drift, so the table is
generated from showcase/*.json between markers, and tests/test_method_tables.py
fails if the committed file is stale.

    python -m scripts.method_tables            # rewrite the block in place
    python -m scripts.method_tables --check    # exit 1 if it is out of date
"""
from __future__ import annotations

import argparse
import json
import os
import sys

DOC = os.path.join("docs", "METHOD.md")
SHOWCASE = "showcase"
BEGIN = "<!-- BEGIN known-answer table (generated by scripts/method_tables.py) -->"
END = "<!-- END known-answer table -->"
P_BEGIN = "<!-- BEGIN power table (generated by scripts/method_tables.py from showcase/power.json) -->"
P_END = "<!-- END power table -->"

SIGNAL_UNITS = {"VV": " dB", "VH": " dB", "RATIO": " dB"}
VERDICT_WORD = {"REAL": "**REAL**", "NOT_REAL": "NOT REAL", "CANT_TELL": "CAN'T TELL",
                "PARTIAL": "PARTIAL", "BASELINE": "BASELINE"}


def _fmt(v, signal):
    if v is None:
        return "—"
    u = SIGNAL_UNITS.get(signal, "")
    return f"{v:+.2f}{u}"


def build() -> str:
    with open(os.path.join(SHOWCASE, "index.json"), encoding="utf-8") as f:
        index = json.load(f)
    rows = ["| Site | Type | Expected | Verdict | Mode | Lead signal | Effect (90% interval) | Placebo p |",
            "|---|---|---|---|---|---|---|---|"]
    n = hits = cant = misses = false_alarms = 0
    for e in index:
        p = os.path.join(SHOWCASE, f"{e['id']}.json")
        if not os.path.exists(p):
            continue
        with open(p, encoding="utf-8") as f:
            r = json.load(f)
        lead = r["verdict"]["lead_signal"]
        s = (r.get("signals") or {}).get(lead) or {}
        got = r["verdict"]["status"]
        exp = e.get("expected")
        interval = "—"
        if s.get("lo") is not None and s.get("hi") is not None:
            interval = f"{_fmt(s.get('point'), lead)} ({_fmt(s['lo'], lead)} to {_fmt(s['hi'], lead)})"
            if abs(float(s["hi"]) - float(s["lo"])) < 1e-9:
                interval += " — degenerate, not a precise estimate"
        pp = s.get("placebo_p")
        pp_s = "—" if pp is None else f"{float(pp):.3f}"
        site = e.get("label", e["key"]).split(":")[0]
        rows.append(f"| {site} | {e.get('type', '—')} | {exp or '—'} | "
                    f"{VERDICT_WORD.get(got, got)} | {r.get('mode') or 'ring'} | "
                    f"{lead or '—'} | {interval} | {pp_s} |")
        if exp:
            n += 1
            if got == "CANT_TELL":
                cant += 1
            elif got == exp:
                hits += 1
            elif exp == "NOT_REAL":
                false_alarms += 1
            else:
                misses += 1
    body = "\n".join(rows)
    summary = (f"\n**{n} sites counted: {hits} correct, {misses} missed, {false_alarms} false alarms, "
               f"{cant} can't tell.** The can't-tell count is the honest headline here"
               f"{': it is larger than the number of correct calls' if cant > hits else ''}, and a clean "
               f"\"0 misses, 0 false alarms\" should be "
               f"read alongside it, because a failure to detect lands in can't-tell rather than in "
               f"misses. Sites remain candidates until confirmed. Generated from the committed runs in "
               f"`showcase/` by `scripts/method_tables.py`; `showcase/track_record.json` is the same "
               f"data and must agree.\n")
    return f"{BEGIN}\n\n{body}\n{summary}\n{END}"


def build_power() -> str:
    """Detection power under both placebo procedures, from showcase/power.json."""
    with open(os.path.join(SHOWCASE, "power.json"), encoding="utf-8") as f:
        pw = json.load(f)
    a = pw["area"]
    unit = {"NDVI": "", "VH": " dB"}
    rows = ["| Signal | Injected effect | REAL, symmetric placebo (current) | REAL, asymmetric placebo (old) |",
            "|---|---|---|---|"]
    for sig in ("NDVI", "VH"):
        sym = {r["effect"]: r for r in pw[sig]["symmetric"]}
        asym = {r["effect"]: r for r in pw[sig]["asymmetric"]}
        for eff in sorted(sym, reverse=True):
            cell = lambda r: f"{r['detected']} / {r['n']}" + (" (false alarms)" if eff == 0 else "")
            rows.append(f"| {sig} | {eff:+.2f}{unit[sig]} | {cell(sym[eff])} | {cell(asym[eff])} |")
    head = (f"Real, untouched cells around the Midlands test area (bbox {a['bbox']}, {a['window'][0]} to "
            f"{a['window'][1]}, {a['cells']} cells; {a['s2_observations']} clear optical and "
            f"{a['s1_observations']} radar observations). {pw['procedure']} Both procedures run on the "
            f"same cache, so the columns differ only in the placebo test. {a['note']}")
    return f"{P_BEGIN}\n\n{head}\n\n" + "\n".join(rows) + f"\n\n{P_END}"


def _splice(doc: str, begin: str, end: str, block: str) -> str | None:
    if begin not in doc or end not in doc:
        return None
    i, j = doc.index(begin), doc.index(end) + len(end)
    return doc[:i] + block + doc[j:]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    with open(DOC, encoding="utf-8") as f:
        doc = f.read()
    new = _splice(doc, BEGIN, END, build())
    if new is None:
        print(f"markers not found in {DOC}; add them around the known-answer table", file=sys.stderr)
        return 2
    if os.path.exists(os.path.join(SHOWCASE, "power.json")):
        new2 = _splice(new, P_BEGIN, P_END, build_power())
        if new2 is None:
            print(f"power-table markers not found in {DOC}", file=sys.stderr)
            return 2
        new = new2
    if a.check:
        if new != doc:
            print(f"{DOC} is out of date; run `python -m scripts.method_tables`", file=sys.stderr)
            return 1
        print(f"{DOC} known-answer and power tables are up to date")
        return 0
    with open(DOC, "w", encoding="utf-8") as f:
        f.write(new)
    print(f"rewrote the known-answer and power tables in {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
