"""Regenerate the known-answer table in docs/METHOD.md from the committed runs.

Three tables in this repo drifted apart: docs/METHOD.md section 10,
showcase/track_record.json and showcase/validation.md disagreed on Rhodes'
verdict and on Grunheide's interval, because METHOD.md was written by hand and
the showcase runs moved underneath it (Rhodes was re-run in wide mode and became
REAL). Hand-editing it again would just restart the drift, so the table is
generated from showcase/*.json between markers, and tests/test_method_tables.py
fails if the committed file is stale.

    python -m scripts.method_tables            # rewrite the block in place
    python -m scripts.method_tables --check    # exit 1 if it is out of date
"""
from __future__ import annotations

import argparse
import json
import os
import sys

DOC = os.path.join("docs", "METHOD.md")
SHOWCASE = "showcase"
BEGIN = "<!-- BEGIN known-answer table (generated by scripts/method_tables.py) -->"
END = "<!-- END known-answer table -->"

SIGNAL_UNITS = {"VV": " dB", "VH": " dB", "RATIO": " dB"}
VERDICT_WORD = {"REAL": "**REAL**", "NOT_REAL": "NOT REAL", "CANT_TELL": "CAN'T TELL",
                "PARTIAL": "PARTIAL", "BASELINE": "BASELINE"}


def _fmt(v, signal):
    if v is None:
        return "—"
    u = SIGNAL_UNITS.get(signal, "")
    return f"{v:+.2f}{u}"


def build() -> str:
    with open(os.path.join(SHOWCASE, "index.json")) as f:
        index = json.load(f)
    rows = ["| Site | Type | Expected | Verdict | Mode | Lead signal | Effect (90% interval) | Placebo p |",
            "|---|---|---|---|---|---|---|---|"]
    n = hits = cant = misses = false_alarms = 0
    for e in index:
        p = os.path.join(SHOWCASE, f"{e['id']}.json")
        if not os.path.exists(p):
            continue
        with open(p) as f:
            r = json.load(f)
        lead = r["verdict"]["lead_signal"]
        s = (r.get("signals") or {}).get(lead) or {}
        got = r["verdict"]["status"]
        exp = e.get("expected")
        interval = "—"
        if s.get("lo") is not None and s.get("hi") is not None:
            interval = f"{_fmt(s.get('point'), lead)} ({_fmt(s['lo'], lead)} to {_fmt(s['hi'], lead)})"
            if abs(float(s["hi"]) - float(s["lo"])) < 1e-9:
                interval += " — degenerate, not a precise estimate"
        pp = s.get("placebo_p")
        pp_s = "—" if pp is None else f"{float(pp):.3f}"
        site = e.get("label", e["key"]).split(":")[0]
        rows.append(f"| {site} | {e.get('type', '—')} | {exp or '—'} | "
                    f"{VERDICT_WORD.get(got, got)} | {r.get('mode') or 'ring'} | "
                    f"{lead or '—'} | {interval} | {pp_s} |")
        if exp:
            n += 1
            if got == "CANT_TELL":
                cant += 1
            elif got == exp:
                hits += 1
            elif exp == "NOT_REAL":
                false_alarms += 1
            else:
                misses += 1
    body = "\n".join(rows)
    summary = (f"\n**{n} sites counted: {hits} correct, {misses} missed, {false_alarms} false alarms, "
               f"{cant} can't tell.** The can't-tell count is the honest headline here: it is larger "
               f"than the number of correct calls, and a clean \"0 misses, 0 false alarms\" should be "
               f"read alongside it, because a failure to detect lands in can't-tell rather than in "
               f"misses. Sites remain candidates until confirmed. Generated from the committed runs in "
               f"`showcase/` by `scripts/method_tables.py`; `showcase/track_record.json` is the same "
               f"data and must agree.\n")
    return f"{BEGIN}\n\n{body}\n{summary}\n{END}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    with open(DOC) as f:
        doc = f.read()
    block = build()
    if BEGIN in doc and END in doc:
        i, j = doc.index(BEGIN), doc.index(END) + len(END)
        new = doc[:i] + block + doc[j:]
    else:
        print(f"markers not found in {DOC}; add them around the known-answer table", file=sys.stderr)
        return 2
    if a.check:
        if new != doc:
            print(f"{DOC} is out of date; run `python -m scripts.method_tables`", file=sys.stderr)
            return 1
        print(f"{DOC} known-answer table is up to date")
        return 0
    with open(DOC, "w") as f:
        f.write(new)
    print(f"rewrote the known-answer table in {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
